# Generated by Django 4.2.5 on 2023-09-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_empleado_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='image',
            field=models.ImageField(blank=True, upload_to='empleados/', verbose_name='imagen'),
        ),
    ]
