# Generated by Django 4.2.5 on 2023-09-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_alter_empleado_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('0', 'Contador'), ('1', 'Administrador'), ('2', 'Economista'), ('3', 'Otro'), ('4', 'Secretaria'), ('5', 'Servicios Generales'), ('6', 'Practicante Universitario'), ('7', 'Coordinador')], max_length=1, verbose_name='Trabajo'),
        ),
    ]
